# Generated by Django 6.0.6 on 2026-07-14 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hash_arquivo', models.CharField(max_length=64, unique=True)),
                ('caminho_original', models.CharField(max_length=500)),
                ('caminho_thumb', models.CharField(max_length=500)),
                ('tipo', models.CharField(default='', max_length=10)),
                ('duracao', models.FloatField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('fuso_horario', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rosto',
            name='foto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rostos', to='galeria.midia'),
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
