# Generated by Django 6.0.6 on 2026-07-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_midia_alter_rosto_foto_delete_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='altura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='midia',
            name='largura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='midia',
            name='orientacao',
            field=models.CharField(default='', max_length=10),
        ),
    ]
