# Generated by Django 6.0.6 on 2026-07-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_midia_altura_midia_largura_midia_orientacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='orientacao',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
