# Generated by Django 6.0.6 on 2026-07-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_midia_orientacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midia',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='midia',
            name='longitude',
        ),
    ]
