# Generated by Django 6.0.6 on 2026-07-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_remove_midia_latitude_remove_midia_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
