# Generated by Django 6.0.6 on 2026-07-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_midia_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='pessoas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
