# Generated by Django 6.0.6 on 2026-07-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_midia_pessoas'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='caminho_web',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
